### ISSUE TITLE
Using ConfigureAwait(false)

### ISSUE THREAD

**Issue by stevehansen** [dimitrovdaniel/echosign-rest-net#1]
Since this is used as a library it is recommended to always use ConfigureAwait(false) when awaiting in async methods.

http://stackoverflow.com/questions/30036459/should-we-use-configureawaitfalse-in-libraries-that-call-async-callbacks

Using the library as-is in ASP.NET projects might give us deadlocks/exceptions in the future.

**Comment by dimitrovdaniel** [comment]
Thanks for the tip! Gotta up my async skills.
